version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: ./backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file: ./backend/.env
    volumes:
      - static:/app/static_backend/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    env_file: ./backend/.env
    volumes:
      - static:/result_build/
    command: cp -r /app/dist/. /result_build/
    depends_on:
      - db

  gateway:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    env_file: ./backend/.env
    volumes:
      - static:/staticfiles/
      - media:/mediafiles/
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
