version: '3.3'

volumes:
  static:
  media:
  pg_data:

services:

  db:
    image: postgres:13.10-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - static:/app/static/
      - media:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    env_file: .env
    command: cp -r /app/dist/. /static_frontend/
    volumes:
      - static:/static_frontend

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/app/media/
    depends_on:
      - backend
      - frontend
      - db
