version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKERHUB_USERNAME}/${PROJECT_NAME}_backend
    env_file: .env
    volumes:
      - static:/static_backend/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: ${DOCKERHUB_USERNAME}/${PROJECT_NAME}_frontend
    env_file: .env
    command: cp -r /app/dist/. /static_frontend/
    volumes:
      - static:/static_frontend
    depends_on:
      - db

  gateway:
    image: ${DOCKERHUB_USERNAME}/${PROJECT_NAME}_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media/
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
